name: 'Debug Inputs'
description: 'Debugging inputs'
inputs:
  debug_context:
    description: "Also debug the full github context"
    required: false
    default: 'false'
  job_summary:
    description: "Print a table with the inputs in the job summary"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Display inputs
      run: echo "${{ toJson(github.event.inputs || inputs) }}"
      shell: bash

    - name: Display Context
      if: inputs.debug_context == 'true'
      run: echo "${{ toJson(github) }}"
      shell: bash

    - name: Generate Summary
      if: inputs.job_summary == 'true'
      run: |
        echo '# INPUTS' >> $GITHUB_STEP_SUMMARY
        echo '| Variable Name | Value |' >> $GITHUB_STEP_SUMMARY
        echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
        echo '${{ toJson(github.event.inputs || inputs) }}' | jq -r 'to_entries[] | "|\(.key)| \(.value)|"' >> $GITHUB_STEP_SUMMARY
      shell: bash
