
name: Test debug
on:
  workflow_dispatch:
    inputs:
      toto:
        required: false
        description: toto
        default: toto
  workflow_call:
    inputs:
      toto:
        required: false
        description: toto
        default: toto
        type: string
    
jobs:
  test-debug:
    name: Run-test    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: ls
      - name: Test debug
        uses: akur8-oss/ga-display-inputs@v1.0

      - run: echo "${{ toJson(github.event.inputs || inputs) }}"
      - run: echo "${{ toJson(inputs) }}"
      - run: echo "${{ toJson(github) }}"

      - run: |
          echo '# INPUTS'
          echo '| Variable Name | Value |'
          echo '| --- | --- |'
          echo '${{ toJson(github.event.inputs || inputs) }}' | jq -r 'to_entries[] | "|\(.key)| \(.value)|"'
